# Generated by Django 5.0.3 on 2024-04-16 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_attributevariant_modified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attributevariant",
            old_name="name",
            new_name="attribut_vaiant_name",
        ),
        migrations.RenameField(
            model_name="attributevariant",
            old_name="attribute",
            new_name="variant",
        ),
    ]
