# Generated by Django 5.0.3 on 2024-04-16 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_rename_name_attributevariant_attribut_vaiant_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attributevariant",
            old_name="attribut_vaiant_name",
            new_name="attribut_variant_name",
        ),
    ]
