# Generated by Django 5.0.3 on 2024-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "store",
            "0007_rename_attribut_vaiant_name_attributevariant_attribut_variant_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevariant",
            name="attribut_variant_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
