# Generated by Django 5.0.3 on 2024-04-18 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_cartitem_variants_attribut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variants_attribut",
        ),
    ]
