# Generated by Django 5.0.3 on 2024-04-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_cartitem_variants_attribut"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variant_key",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name="CartVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_key", models.CharField(max_length=250, unique=True)),
                (
                    "cartitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant",
                        to="carts.cartitem",
                    ),
                ),
            ],
        ),
    ]
