# Generated by Django 5.0.3 on 2024-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0006_cartitem_variant_key_cartvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variant_key",
            field=models.CharField(
                blank=True, default=None, max_length=10, unique=True
            ),
        ),
    ]
